sonar-project.properties

Sonar analysis requires compiled Java classes to do analysis. The Java
files provided are snippets that are nto compiled so exlucing them.

Ignore java files for Sonar analysis #17

---

CHANGELOG.md
examples/terminal.example.didact.md
package.json
src/extension.ts
src/extensionFunctions.ts
src/test/suite/extensionFunctions.test.ts

issue #46 - adding sendNamedTerminalCtrlC command with example

---

src/extensionFunctions.ts
src/utils.ts

Updates the getCurrentFileSelectionPath to use active editor. This helps when commands are invoked through keyboard shortcuts and command palette.
This also enables to run the extension on Eclipse Che.

use active editor to deduce uri

---

README.md

With RHMI 2, the repo has changed to support Solution Patterns naming

change links to Integreatly walkthroughs

---

src/didactWebView.ts
src/extension.ts
src/utils.ts

Expanding on https://github.com/redhat-developer/vscode-didact/pull/127, this change actually persists the view column when it gets moved so the next time a didact view opens it opens in a consistent manner. 

Issue #101 - Persist current column for webview

---

JenkinsFile

to workaround microsoft/vscode#99492

FUSETOOLS2-490 - use rhel8 instead of rhel 7 node

---

CHANGELOG.md
examples/copyFileURL.example.didact.md
package-lock.json
package.json
src/commandHandler.ts
src/extension.ts
src/extensionFunctions.ts
src/test/suite/extensionFunctions.test.ts

file from a URL, rename it, put it into a folder, and even unzip it

issue #34 and #35 - adding new command to pull a

---

src/commandHandler.ts
src/test/suite/commandHandler.test.ts

For instance, when opening a file 
```
[Open the org.quickperf.jvm.JvmAnnotationsJunit4Test class](didact://?commandId=vscode.open&projectFilePath=jvm-junit4%2Fsrc%2Ftest%2Fjava%2Forg%2Fquickperf%2Fjvm%2FJvmAnnotationsJunit4Test.java&number=2)
```
it would pass the number 2 as the second argument of `vscode.open` (columnOrOptions is expecting a number)
> vscode.open - Opens the provided resource in the editor.
>
> resource - Resource to open
> columnOrOptions - (optional) Either the column in which to open or editor options, see vscode.TextDocumentShowOptions

Allowing number to be passed as a command argument

---

CHANGELOG.md
media/main.js
package.json
src/didactWebView.ts
src/doublyLinkedList.ts
src/extension.ts
src/extensionFunctions.ts
src/history.ts
src/test/suite/extensionFunctions.test.ts

Adds a very basic history to the Didact window. It re-opens the files and is not caching the HTML, but does cache the URIs used. Note that the cache is reset to the last didact file opened at workspace closing time if it is available. Otherwise, the history is empty each time the workspace starts. 
To test:
* open a few didact files from the didact view
* use ctrl+shift+left to go back in the history (it loops back from the first item to the last)
* use ctrl+shift+right to go forward in the history (it loops forward from the last item to the first)
* leave a didact file open, close the workspace
* reopen the workspace, add a different didact, the cached didact file should be first in the history

Issue102 adding history

---

src/didactWebView.ts

FUSETOOLS2-689 - fixing webview disposed error

---

.travis.yml
JenkinsFile

it allows to ensure that the package-lock.json is respected

FUSETOOLS2-703 - use npm ci instead of npm install

---

JenkinsFile

it allows to have the poll in Pipeline Job to be working

FUSETOOLS2-784 - use .git suffix for git url

---

CHANGELOG.md
src/asciidocUtils.ts
src/extensionFunctions.ts
src/test/data/include.asciidoc.txt
src/test/data/includetext.didact.adoc
src/test/suite/asciidocUtilsTest.test.ts

Addresses the issue discovered by @pwright when adding AsciiDoc `include` directives. 
To define the use case: As a Didact tutorial developer using AsciiDoc, I want to be able to break up my Didact file and use `include` directives to pull multiple files into the final document that is rendered in the Didact webview.
A limitation at this point will be that if I have a Didact file with included files, those files will need to be in the directory alongside the main Didact.adoc file or in a folder relative to the path of the main Didact.adoc file.
So if I have a file structure like
```
project
│   root.didact.adoc
│   include1.adoc    
│
└───moreincludes
│   include2.adoc
```
You could then include either of the following file references in root.didact.adoc
```
include::include1.adoc[] …
```

Fusetools2 804 fixing asciidoc includes

---

src/extensionFunctions.ts
src/test/suite/extensionFunctions.test.ts

problem. It was unaware of url differences when processing Didact files

FUSETOOLS2-806 - addressing getDataFromUrl

---

CHANGELOG.md
src/commandHandler.ts
src/test/suite/commandHandler.test.ts

- missing tests
- need to determine if list of json needs to be handled similarly to text/user/number
- need to determine if it is a common practice
with that, we can use commands that are using json as arguments for instance:
`[rename terminal](didact://?commandId=workbench.action.terminal.renameWithArg&json=\{"name":"aNewName"\})`

FUSETOOLS2-832 - allow passing json parameter to commands

---

CHANGELOG.md
src/extensionFunctions.ts
src/scaffoldUtils.ts
src/test/data/scaffoldOpen.json
src/test/suite/didact.test.ts

Essentially we just want to add an option to files specified in the json for project scaffolding. If open = true, we will open the file beside the currently open editor (or window) rather than overwrite any other text editor that might be open.
Adding `"open" : true` to a file entry in the project json will open it in a new text editor window in the "next" column beside the currently open file/editor. Note that if the option is unspecified, it defaults to "false". 
It would be good practice to only open one file during the process of scaffolding, but conceivably a scaffold file could open an indefinite number of files, each in a new text editor pane.

FUSETOOLS2-742 - adding new open option for scaffolding

---

src/didactUriCompletionItemProvider.ts
src/test/suite/didactUriCompletionItemProvider.test.ts

Problem was with regex pattern matching and testing of the `link:` style links for asciidoc. Tweaked the regex and added some tests. 

FUSETOOLS2-845 fixing link matcher

---

src/test/suite/markdownUtils.test.ts

"not covered by tests"
https://sonarcloud.io/code?id=vscode-didact&selected=vscode-didact%3Asrc%2FmarkdownUtils.ts

FUSETOOLS2-874 - adding test for markdownutils

---

media/webviewslim.css

Discovered a slight bug with the layout of the footer cutting off the bottom of the text... 
Without the fix, you can see the bottom line of the tutorial gets cut off:
With the fix (adding 10px more): 

FUSETOOLS-920 - adjusting bottom margin

---

src/nodeProvider.ts

Follows up https://github.com/redhat-developer/vscode-didact/pull/331 and requires the logo.svg that is in that PR to show the icons in the tree. If the icon is missing from the extension folder, the icons do not show in the tree.

FUSETOOLS2-920 - add didact icon to the tree

---

demos/markdown/tutorial/tutorial.didact.md

"Insert Requirements label" -> "Insert Didact Requirements label"

Fix completion naming in tutorial

---

CHANGELOG.md
package-lock.json
package.json

updating version to 0.3.1

---

media/webviewslim.css

added `padding-bottom: 25px` to `.tutorialContent` CSS as described here https://www.freecodecamp.org/news/how-to-keep-your-footer-where-it-belongs-59c6aa05c59c/
The issue was that there wasn't enough padding in the middle. The page is structured like:
```
<head>...</head>
<body class="content">
<div class="tutorialContent">
... tutorial content rendered from Markdown or AsciiDoc
</div>
<div class="didactFooter">...footer content...</div>
</body>
```
I had padding in the content CSS, but not in the tutorialContent CSS. So we were not quite adjusting the tutorialContent correctly.
Minor fix. 

FUSETOOLS2-997 - add 25px pad to .tutorialContent to fix occluded last line

---

src/extensionFunctions.ts

Initially we were throwing an error if we found a terminal that already exists (see https://github.com/redhat-developer/vscode-didact/blob/98080df3e0d47467b01f322ce066300feab32984/src/extensionFunctions.ts#L158)
Now we just show the terminal if it already exists, which is the gentler approach.

FUSETOOLS2-996 - instead of erroring out, open terminal if it exists

---

src/extensionFunctions.ts
src/test/suite/stubDemoTutorial.test.ts

between show and send
This was needed to resolve a timing issue we repeatedly were seeing in https://github.com/redhat-developer/vscode-didact/pull/437/checks?check_run_id=1973172348:
```
1) stub out a tutorial
that we can send an echo command to the terminal and get the response:
AssertionError: expected 'Windows PowerShell\r\nCopyright (C) Microsoft Corporation. All rights reserved.' to include 'Hello World echoTerminal'
at d:\a\vscode-didact\vscode-didact\out\test\suite\stubDemoTutorial.test.js:107:38
at Generator.next (<anonymous>)
at fulfilled (d:\a\vscode-didact\vscode-didact\out\test\suite\stubDemoTutorial.test.js:21:58)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

FUSETOOLS2-1014 - adding small delay

---

src/test/suite/stubDemoTutorial.test.ts

Used the approach from @apupier here - https://github.com/redhat-developer/vscode-didact/pull/452 and made one change to ensure that we found the right active terminal. 
Number of successful repetitive builds: 3 
Then
```
SIGSEGV
Exit code:   SIGSEGV
Failed to run tests
```
Then...
Successful repetitions: 3
I think this may be the right combination. SIGSEGV we can't really account for since that's a system fault. 

FUSETOOLS2-1021 - fixing flaky windows test

---

src/didactPanel.ts

Removed unused extensions import from didactPanel
https://sonarcloud.io/project/issues?fileUuids=AXdPCJCO1d9Oa98Oz9lC&id=vscode-didact&resolved=false&types=CODE_SMELL

FUSETOOLS2-1010 - removing unused import

---

CHANGELOG.md
examples/register-tutorial.project.json
examples/registry.example.didact.md
package-lock.json
package.json
src/extension.ts
src/extensionFunctions.ts
src/nodeProvider.ts
src/test/suite/didactUriCompletionItemProvider.test.ts
src/test/suite/extension.test.ts
src/test/suite/registry.test.ts
src/test/suite/registryWorkspace.test.ts
src/utils.ts

This will be a multiple commit project and this is the first chunk of work.
First commit adds:
* New setting to Automatically add the default Didact tutorials at startup if they are not present
* New command vscode.didact.registry.clear (not shown in the Didact Tutorials view, but present in the Command Palette)
* New command vscode.didact.registry.addJson used to add a new tutorial to the registry (JSON looks like ```{
"name" : `tutorial name`,
"category" : `exact category name`,
"sourceUri" : `file/http URI to file`,
};```)
* New tests validate these additional functions and verify that the older registerTutorialWithCategory method still works (though it now hands off to a registerTutorialWithArgs method)
* Added a class to handle the name/category/uri details for a new tutorial to more …

FUSETOOLS2-1034 - tutorial registry updates

---

src/test/suite/registry.test.ts
src/utils.ts

While going through documenting the process of adding new tutorials to the registry, it became very apparent we needed to add a final "are you sure?" check when they use the command to clear the registry.

FUSETOOLS2-1064 - add confirmation to clear

---

src/test/suite/completions.test.ts
src/test/suite/stubDemoTutorial.test.ts

Testing the work that @lhein did with https://github.com/redhat-developer/vscode-didact/pull/501 in a rebased branch with latest changes to fix the stub tests for terminal 
But also found a fix for the completion test that was hanging us up, borrowing a couple of methods from a Microsoft test harness (links included in code comments)

FUSETOOLS2-1051 - fixing flaky tests in stub and completion

---

examples/vscode-links.didact.md
package.json
src/extension.ts
src/extensionFunctions.ts
src/test/suite/didact.test.ts
src/test/suite/didactUriCompletionItemProvider.test.ts

to register an https-based tutorial with name and category
added more `vscode://` link support and the beginning of calling different didact commands from a web link
Still exploring how to make a `vscode://` link not get ignored in a GitHub markdown file, but for now we can copy the text of the command from the web browser and use the `Didact: Process vscode link from web` to pick up the Uri from the clipboard or enable the user to paste it in. 
These links work fine inside a Didact window, but trying to make them work from outside is a bit more difficult. 
The web page in the demo is hosted here: https://github.com/bfitzpat/didact-tutorials/blob/main/README.md. But the idea is to provide a repository where devs and tutorial authors can create easy links to add to their Didact Tutorials …

FUSETOOLS2-1063 - extend uri handler

---

CHANGELOG.md
package.json
src/extension.ts
src/extensionFunctions.ts
src/test/suite/didactUriCompletionItemProvider.test.ts

text to CLI (with URLencoding;  no validation that it's a valid command line string)

FUSETOOLS2-1067 - add key shortcut to convert

---

src/extensionFunctions.ts

Small sonar issue missed in the first pass
https://sonarcloud.io/project/issues?id=vscode-didact&open=AXmjwvWa8trMiAr3VkkB&resolved=false&severities=MINOR

removing unused DIDACT_DEFAULT_URL import

---

docs/troubleshooting.md

I believe this issue was caused by my exercising new feature at https://code.visualstudio.com/updates/v1_58#_terminals-in-the-editor-area
Altho I had to mess around to get things going, so not 100% sure

Encountered issue with editor view

---

src/extension.ts
src/test/suite/registry.test.ts
src/test/suite/stubDemoTutorial.test.ts
src/utils.ts

Spun this change out of https://github.com/redhat-developer/vscode-didact/pull/551 (the OpenShift Quick Start PoC)
For additional details see https://issues.redhat.com/browse/FUSETOOLS2-1203

Fusetools2 1203 adding tuts thru ENV variable

---

.circleci/config.yml

circleci/* are deprecated and to be replaced with cimg/*

FUSETOOLS2-1290 - migrate Docker image on Circle CI

---

CHANGELOG.md
src/utils.ts

extensions
this is straightforward, not very flexible and covers only the case of
users that has not changed the auto-reload on startup embedded
tutorials. Having a proper registry handling all the kinds of tutorials
would be better but given allocated time on VS Code Didact and impact of
other fixes not yet released and as this fix is working in default case
I think we should go with this "mitigation fix" and consider to be in a
releasable state.
how to test:
- install Didact 0.4.0
- build a didact 0.4.1 vsix locally from this PR branch
- install the 0.4.1 vsix
- restart (and not only reload otherwise the extension cache folder is not cleared by VS Code)
- open a didact tutorial.

FUSETOOLS2-1160 - partial fix for embedded tutorial between upgrade of

---

src/Telemetry.ts
src/extensionFunctions.ts
src/test/suite/_extension.test.ts
src/test/suite/completions.test.ts
src/test/suite/registry.test.ts
src/utils.ts

before:
```
(base) [apupier@localhost vscode-didact]$ npm run compile
> vscode-didact@0.4.1 compile /home/apupier/git/vscode-didact
> tsc -p ./ && npm run lint
> vscode-didact@0.4.1 lint /home/apupier/git/vscode-didact
> eslint src --ext .ts
/home/apupier/git/vscode-didact/src/Telemetry.ts
33:2  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types
44:2  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types
/home/apupier/git/vscode-didact/src/asciidocUtils.ts
20:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
24:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
/home/apupier/git/vscode-didact/src/commandHandler.ts
28:17  warning …
```

FUSETOOLS2-841 - provide fix for several warnings pointed by linter
