redhat-developer/vscode-didact

package.json, src/extension.ts, src/extensionFunctions.ts, src/nodeProvider.ts, src/test/suite/didact.test.ts, src/test/suite/registry.test.ts, src/utils.ts
=> adding didact registry and view

README.md, package-lock.json, package.json, src/commandHandler.ts, src/extensionFunctions.ts, src/test/suite/didact.test.ts, src/utils.ts
=> adds a new path type - extFilePath - and tests

demo/didact-demo.md, media/webviewslim.css, src/didactWebView.ts, src/extension.ts
=> switching to bulma framework for css and light mode background

src/didactWebView.ts, src/extension.ts, src/extensionFunctions.ts
=> persist tutorial html and title between sessions

.gitignore, .travis.yml, package.json, src/test/runTest.ts, src/test/suite/extension.test.ts, tsconfig.json
=> adding travis configuration

package-lock.json, package.json, src/asciidocUtils.ts, src/didactWebView.ts, src/extensionFunctions.ts, src/test/suite/didact.test.ts
=> adding asciidoc again and working on test failure

.travis.yml, JenkinsFile, README.md
=> adding badges to readme, jenkinsfile, and updating sonarcloud org

package-lock.json, package.json
=> update package version to 0.1.3 and clean up package details

src/test/suite/didact.test.ts
=> removing maven test and shifting to generic uname for req test

package-lock.json, package.json, src/test/suite/index.ts
=> adding the mocha tests reporter

package.json
=> updating version to 0.1.5 for future development

sonar-project.properties
=> Provide Sonar project key and name #17

package-lock.json, package.json
=> bumping version to 0.1.6

JenkinsFile
=> Publish sources #43

README.md
=> update readme to point to the new wiki with many more details

.travis.yml, JenkinsFile
=> Remove unused --ignore-script call #40

JenkinsFile
=> Remove unused java from Jenkins file #42

CHANGELOG.md, package.json, src/commandHandler.ts, src/utils.ts
=> issue #35 - adding preference to disable generic completion messages

examples/terminal.example.didact.md, package.json, src/extension.ts, src/extensionFunctions.ts, src/test/suite/extensionFunctions.test.ts
=> issue #49 - adding new command to close a named terminal

CHANGELOG.md, Contributing.md, package-lock.json, package.json
=> updating version to 0.1.7 and adding contribution doc

.vscode/settings.json, package.json, src/extension.ts, src/extensionFunctions.ts, src/test/suite/registry.test.ts, src/utils.ts
=> issue #58 - moving registry to context

examples/requirements.example.didact.md, package.json, src/extension.ts, src/extensionFunctions.ts, src/test/suite/extensionFunctions.test.ts
=> issue #60 - adding new CLI command checker

CHANGELOG.md, package-lock.json, package.json
=> updating version to 0.1.8 and changelog

CHANGELOG.md, demo/didact-demo.didact.md, media/main.js, src/extensionFunctions.ts, src/test/suite/didact.test.ts
- add cliCommandSuccessful to list of reqs commands links to check
- Add new tests and update test markdown file
=> issue #68 - add cliCommandSuccessful back to

CHANGELOG.md, src/didactWebView.ts, src/test/suite/didact.test.ts
- replace cache each time we start a new didact file in the view
- update changelog
=> issue #67 - fix problem with caching that was preventing switching

CHANGELOG.md, package-lock.json, package.json
=> updating to version 0.1.9

CHANGELOG.md, README.md, src/didactUriCompletionItemProvider.ts, src/didactUriCompletionItemProviderAsciiDoc.ts, src/didactUriCompletionItemProviderMarkdown.ts, src/extension.ts, src/extensionFunctions.ts, src/test/suite/didact.test.ts, src/test/suite/didactUri.test.ts, src/test/suite/didactUriCompletionItemProviderAsiiDoc.test.ts, src/test/suite/didactUriCompletionItemProviderMarkdown.test.ts
=> issue #75 - adding autocomplete for asciidoc didact files

media/webviewslim.css, src/didactWebView.ts
=> issue #32 - fixing content security policy for webview

CHANGELOG.md, media/asciidoctor.css, src/didactWebView.ts, src/extensionFunctions.ts
=> adding separate css for asciidoc

README.md, snippets/snippets.json, src/didactWebView.ts, src/extensionFunctions.ts, src/nodeProvider.ts
=> refactoring names to avoid markdown everywhere

CHANGELOG.md, package.json, src/test/suite/extension.test.ts
=> adding key bindings to start didact command

media/webview.css, media/webviewslim.css, src/didactWebView.ts
=> pick up colors from vscode ide color theme

media/webviewslim.css, package.json
=> correcting missing color override and fixing tab in package.json

CHANGELOG.md, package-lock.json, package.json
=> bumping version to 0.1.10

media/webviewslim.css, src/asciidocUtils.ts
Add themed colors for code reference blocks.
=> update css for code

CHANGELOG.md, src/didactWebView.ts
=> dispose web panel instead of reusing it so we reset local resource roots

CHANGELOG.md, package-lock.json, package.json
=> updating version to 0.1.11 for future development

demo/didact-demo.didact.adoc, media/webviewslim.css
=> fixing style issue and items discovered with adoc demo

CHANGELOG.md, package-lock.json, package.json
=> update version to 0.1.12 for future work

CHANGELOG.md, src/commandHandler.ts, src/extensionFunctions.ts, src/test/suite/extensionFunctions.test.ts
=> updating extension path handling when launching didact files

src/extensionFunctions.ts
=> increased timeout for cliExecutionCheck command to 15s

package-lock.json, package.json
=> updating several dependency versions

src/test/suite/extensionFunctions.test.ts
=> fixing paths to various test files in uris

CHANGELOG.md, package-lock.json, package.json, src/test/suite/extensionFunctions.test.ts
=> adding some diagnostic information for jenkins

src/test/suite/extensionFunctions.test.ts
=> adding alternate path for jenkins case

CHANGELOG.md, package-lock.json, package.json
=> bumping version

demos/asciidoc/simple-example.didact.adoc
the  syntax on master  produced weird output for me:
=> fix asciidoc in example

README.md, create_extension/first-tutorial.didact.adoc, demos/asciidoc/didact-demo.didact.adoc, demos/markdown/camelinaction/chapter1/cia2-chapter-1-v2.didact.md, demos/markdown/didact-demo.didact.md
=> deep pass to ensure we link to main didact repo

CHANGELOG.md, package-lock.json, package.json
=> bump version to 0.1.15 and update changelog

package-lock.json, package.json, src/nodeProvider.ts
=> updating vscode version to 1.45 and fixing api breakage

src/didactWebView.ts, src/extensionFunctions.ts
Implements at least part of #101 
Allows for specifying a ViewColumn when showing a tutorial.
=> Allow opening in specific ViewColumn

CHANGELOG.md, src/extensionFunctions.ts
* use find vs. filter to find command id (#123)
* provide number of  commands validated (#124)
* open output log when validating (#125)
=> Improve command validation

CHANGELOG.md, package-lock.json, package.json
=> bumping version to 0.1.6 for future work

.gitignore, .vscode/launch.json, .vscodeignore, src/test/runTest.ts, src/test/suite/didact.test.ts
it allows to detect earlier potential issues with paths
=> FUSETOOLS2-425 - use a workspace with special chars in path for testing

JenkinsFile
=> FUSETOOLS2-343 - publish to open-vsx.org

src/didactWebView.ts, src/test/suite/didactWebView.test.ts
=> fixing default open to avoid didactUri is undefined issue

CHANGELOG.md, package-lock.json, package.json
=> bumping version to 0.1.7 for future development

demos/asciidoc/didact-demo.didact.adoc, demos/markdown/camelinaction/chapter1/cia2-chapter-1-v2.didact.md, demos/markdown/didact-demo.didact.md, demos/markdown/helloJS/helloJS.didact.md, demos/projectwithdidactfile.json, src/didactUriCompletionItemProvider.ts
=> replacing openFolder with open commands

package-lock.json, package.json
=> updating a few dependencies

src/test/suite/didact.test.ts, src/test/suite/extensionFunctions.test.ts, src/utils.ts
=> initial cut at removing files from text fixture

CHANGELOG.md, package-lock.json, package.json, src/didactWebView.ts
=> move to typescript 4.0.2 and switch to xmldom for heading parsing

CHANGELOG.md, demos/markdown/didact-demo.didact.md, src/commandHandler.ts, src/didactUri.ts, src/didactWebView.ts, src/extensionFunctions.ts, src/test/suite/commandHandler.test.ts, src/test/suite/didactUri.test.ts
=> issue #101 - update startDidact command to handle column in link

src/didactWebView.ts, src/test/suite/commandHandler.test.ts
=> FUSETOOLS2-684 - Adding fix to didact column test to unblock master

src/asciidocUtils.ts, src/commandHandler.ts, src/didactUriCompletionItemProvider.ts, src/didactUriCompletionItemProviderAsciiDoc.ts, src/didactUriCompletionItemProviderMarkdown.ts, src/didactWebView.ts, src/doublyLinkedList.ts, src/extension.ts, src/extensionFunctions.ts, src/history.ts, src/markdownUtils.ts, src/nodeProvider.ts, src/scaffoldUtils.ts, src/test/runTest.ts, src/test/suite/commandHandler.test.ts, src/test/suite/didact.test.ts, src/test/suite/didactUri.test.ts, src/test/suite/didactUriCompletionItemProviderAsiiDoc.test.ts, src/test/suite/didactUriCompletionItemProviderMarkdown.test.ts, src/test/suite/didactWebView.test.ts, src/test/suite/extensionFunctions.test.ts, src/test/suite/index.ts, src/test/suite/registry.test.ts, src/utils.ts
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
=> FUSETOOLS2-705 - fixing most of the linter errors

.travis.yml
=> FUSETOOLS2-751 - updating travis node version to keep in sync with jenkins

.travis.yml
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
=> updating nodejs in travis.yml to use latest LTS version

CHANGELOG.md, package-lock.json, package.json
Bumping version from 0.1.17 (new release) to 0.1.18 for new work
=> bumping version to 0.1.18 for next release

README.md
Remove redundant vscode prefix
=> Update name on Readme

README.md
=> FUSETOOLS2-825 - update badge for Travis moving from .org to .com

src/didactWebView.ts
=> FUSETOOLS2-690 - reducing xml warnings

CHANGELOG.md, package-lock.json, package.json
=> updating version to 0.2

.circleci/config.yml
note: 2 tests requires to have the working_directory set to the project
name
=> FUSETOOLS2-855 - Configure Circle CI

Contributing.md
=> FUSETOOLS2-844 - update jenkins link in contributing.md

media/main.js
=> FUSETOOLS2-877 - address inner label

sonar-project.properties
=> FUSETOOLS2-874 updating sonar project props

sonar-project.properties
=> FUSETOOLS2-874 - adjust sonar exclusions

src/nodeProvider.ts
=> FUSETOOLS2-874 - code smells - default parameters should be last in nodeProvider

src/test/suite/asciidocUtilsTest.test.ts
"not covered by tests" 
https://sonarcloud.io/code?id=vscode-didact&selected=vscode-didact%3Asrc%2FasciidocUtils.ts
=> FUSETOOLS2-874 - adding adocutils test

media/webview.css
Addresses sonar reported bugs in webview.css
https://sonarcloud.io/project/issues?id=vscode-didact&open=AXR4WpWr5CyWyJNY-AoB&resolved=false&types=BUG
https://sonarcloud.io/project/issues?id=vscode-didact&open=AXR4WpWr5CyWyJNY-AoC&resolved=false&types=BUG
No noticeable change for user.
=> FUSETOOLS2-874 - fixing NOFRAMES sonar issue

demos/asciidoc/didact-demo.didact.adoc
=> FUSETOOLS2-800 - updating the adoc demo with requirements labels

src/didactUriCompletionItemProvider.ts, src/test/suite/didactUriCompletionItemProvider.test.ts
=> FUSETOOLS2-869 - next round of additional completion tests

src/didactWebView.ts
=> FUSETOOLS2-838 fixing defer warning in webview

src/extensionFunctions.ts, src/markdownUtils.ts, src/test/suite/markdownUtils.test.ts
=> FUSETOOLS2-879 - fixes checkbox attribute spacing

src/test/suite/didactUriCompletionItemProvider.test.ts
=> FUSETOOLS2-869 - removing some delays

media/main.js, media/webview.css, src/didactUriCompletionItemProvider.ts
Addresses these three issues:
media/main.js
https://sonarcloud.io/project/issues?id=vscode-didact&open=AXR4WpWi5CyWyJNY-An_&resolved=false&types=CODE_SMELL
media/webview.css
https://sonarcloud.io/project/issues?id=vscode-didact&open=AXR4WpWr5CyWyJNY-AoA&resolved=false&types=CODE_SMELL
src/didactUriCompletionItemProvider.ts
https://sonarcloud.io/project/issues?id=vscode-didact&open=AXXgrtohLxTnC3qgw1Xh&resolved=false&types=CODE_SMELL
=> FUSETOOLS2-874 - fixing sonar-reported code smells

README.md
=> FUSETOOLS2-855 - add CircleCi Badge in readme

demos/asciidoc/didact-demo.didact.adoc, demos/markdown/didact-demo.didact.md
=> update demo titles to reflect purpose

CHANGELOG.md, package-lock.json, package.json
=> Bump version to 0.2.1

CHANGELOG.md, package-lock.json, package.json, src/didactWebView.ts, src/extension.ts, src/extensionFunctions.ts
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
=> FUSETOOLS2-949 - replaced xmldom dependency with node-html-parser

CHANGELOG.md, package-lock.json, package.json
=> updating version to 0.3.0 for multi-window update

.github/workflows/windows-test.yml
=> adding github action config for windows test

.github/workflows/windows-test.yml, src/test/suite/didactUriCompletionItemProvider.test.ts
=> updating github action config for windows test (#387)

src/test/suite/completions.test.ts, src/test/suite/didactUriCompletionItemProvider.test.ts
=> FUSETOOLS2-969 - Working to fix flaky completion test

CHANGELOG.md, package-lock.json, package.json, src/test/suite/commandHandler.test.ts, src/test/suite/completions.test.ts
=> fixing test timeout

CHANGELOG.md, package-lock.json, package.json
=> updating version to 0.3.2

src/test/suite/didact.test.ts
=> fixing failing test on Darwin os

.github/workflows/macos-test.yml
=> FUSETOOLS2-983 - adding a mac build github action

src/extensionFunctions.ts, src/test/suite/Utils.ts, src/test/suite/demoTutorials.test.ts
Added tests to ensure that the tutorials that we register are tested to verify that all expected command Ids are present and supported.
=> FUSETOOLS2-737 - adding first round of provided tutorial tests

CHANGELOG.md, package.json, src/didactPanel.ts, src/extension.ts, src/extensionFunctions.ts, src/test/suite/didactUriCompletionItemProvider.test.ts
=> issue 415 adding retry and refresh

package-lock.json, package.json, src/commandHandler.ts, src/didactUri.ts, src/extensionFunctions.ts, src/test/suite/Utils.ts, src/test/suite/didact.test.ts
=> FUSETOOLS2-1010 - migrate to url-parse

src/test/suite/completions.test.ts, src/test/suite/stubDemoTutorial.test.ts
=> FUSETOOLS2-737 - Adding tests to validate action results from demo tutorial

src/commandHandler.ts, src/didactManager.ts, src/didactPanel.ts, src/extension.ts, src/extensionFunctions.ts, src/markdownUtils.ts, src/scaffoldUtils.ts, src/test/suite/registry.test.ts, src/utils.ts
=> FUSETOOLS2-1010 - working on some sonar code smells

src/extensionFunctions.ts, src/test/suite/stubDemoTutorial.test.ts
Addresses some redundant await issues
Also using this PR in an attempt to solve the windows test timeout issue. 
=> FUSETOOLS2-1010 - fixing more code smells

CHANGELOG.md, src/didactPanel.ts
=> FUSETOOLS2-997 removing footer

media/main.js
in main.js
https://sonarcloud.io/project/issues?fileUuids=AXR4WpMl5CyWyJNY-Anv&id=vscode-didact&resolved=false&types=CODE_SMELL
Adjusted the two for-of issues and attempted to reduce the complexity of the function by breaking down the event handler into a couple of sub-functions. Due to the monolithic state of the function, I am not sure what else can do. 
=> FUSETOOLS2-1010 - addressing code smells

CHANGELOG.md, package-lock.json, package.json
=> updating version to 0.3.3

src/didactManager.ts, src/extension.ts, src/extensionFunctions.ts, src/nodeProvider.ts, src/test/suite/nodeProvider.test.ts, src/test/suite/registryWorkspace.test.ts, src/utils.ts
=> FUSETOOLS2-1050 - Refactor tree nodes to avoid any

package-lock.json, package.json
Responding to https://github.com/redhat-developer/vscode-didact/security/dependabot/package-lock.json/y18n/open
=> CVE-2020-7774 - fixing y18n security vulnerability

src/extensionFunctions.ts, src/test/suite/stubDemoTutorial.test.ts
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
=> FUSETOOLS2-1051 - minor tweaks to functions / tests related to sendTextToTerminal

src/didactPanel.ts, src/extensionFunctions.ts
=> FUSETOOLS2-1072 - fix refresh of existing window

docs/FAQ.md, docs/_config.yml, docs/autocomplete.md, docs/available-commands.md, docs/constructing-links.md, docs/how-to-use-didact.md, docs/index.md, docs/registering-tutorials.md, docs/scaffolding.md, docs/settings.md, docs/tech-details.md, docs/time-estimates.md, docs/troubleshooting.md, docs/writing-a-tutorial.md
=> moving docs from wiki to GH pages

docs/autocomplete.md, docs/how-to-use-didact.md, docs/index.md, docs/settings.md
=> fixing docpage image links

.vscodeignore
=> FUSETOOLS2-1078 - remove extra artifacts from vsix

src/extension.ts, src/extensionFunctions.ts, src/nodeProvider.ts, src/utils.ts
addressing
* https://sonarcloud.io/project/issues?id=vscode-didact&open=AXkYznwhZeyL3amb-TkF&resolved=false&types=CODE_SMELL
* https://sonarcloud.io/project/issues?id=vscode-didact&open=AXipDPH-a-V4saTdTi_r&resolved=false&types=CODE_SMELL
* https://sonarcloud.io/project/issues?id=vscode-didact&open=AXjK7irKLiYmPkS7sGe9&resolved=false&types=CODE_SMELL
* https://sonarcloud.io/project/issues?id=vscode-didact&open=AXipDPF2a-V4saTdTi_l&resolved=false&types=CODE_SMELL
* https://sonarcloud.io/project/issues?id=vscode-didact&open=AXh-Rr3DIpn87kBcfgto&resolved=false&types=CODE_SMELL
* https://sonarcloud.io/project/issues?id=vscode-didact&open=AXjK7irKLiYmPkS7sGe-&resolved=false&types=CODE_SMELL
* https://sonarcloud.io/project/issues?id=vscode-didact&open=AXipDPF2a-V4saTdTi_o&resolved=false&types=CO …
=> addressing some sonar fixes

src/extension.ts, src/utils.ts
=> FUSETOOLS2-741 - factorize code of registration of embedded tutorials

.gitattributes, package-lock.json, src/test/suite/stubDemoTutorial.test.ts
Adding .gitattributes file per discussion in https://issues.redhat.com/browse/FUSETOOLS2-1161
=> FUSETOOLS2-1161 - adding gitattributes

CHANGELOG.md, README.md, USAGE_DATA.md, package-lock.json, package.json, src/Telemetry.ts, src/commandHandler.ts, src/didactManager.ts, src/extension.ts, src/test/runTest.ts, src/utils.ts
Early work on this, but a good first step. Since we don't quite have a great handle on how to test with the new telemetry framework yet, we'll add tests in a separate PR. 
Based this work on https://github.com/redhat-developer/vscode-redhat-telemetry#how-to-use-this-library  and https://github.com/camel-tooling/vscode-camelk/pull/807 
Sample report here:
https://snapshot.woopra.com/5GeHozdVXv4ujHQiSj2iqrZvUM4mDnB8gjiERhfb5inixSiLdufJR6k8mgqKBEjTo6
(There are many other things we can add to the report, such as platform, locale, etc., but this was a simple example to start from.)
=> Fusetools2 1150 adding telemetry

package-lock.json, package.json, src/test/suite/completions.test.ts, src/test/suite/stubDemoTutorial.test.ts, src/utils.ts
Still wondering about the null argument, but it enabled me to clean up the code and avoid duplication anyway... 
This would supersede https://github.com/redhat-developer/vscode-didact/pull/651
=> Bump types node to 16.3.3

src/utils.ts
now that https://github.com/DefinitelyTyped/DefinitelyTyped/issues/54285
is fixed
=> FUSETOOLS2-1228 - remove workaround on setTimeout

.github/workflows/macos-test.yml, .github/workflows/windows-test.yml
Advantages:
* more readbale
* seems faster: went from 9s to 5s for node setup and cache related tasks
=> FUSETOOLS2-1198 - use built-in caching mechanism for npm

.github/workflows/macos-test.yml, .github/workflows/windows-test.yml, JenkinsFile
=> FUSETOOLS2-1413 - specify node 14 where possible in CI

src/extensionFunctions.ts
to align with current implementation
=> FUSETOOLS2-1008 - fix description of method

CHANGELOG.md, create_extension/create-new-tutorial-with-extension.didact.md
=> 724 - Better align tutorial description with effective snippet code

examples/commands.reference.adoc, examples/terminal.example.didact.md, resources/didactCompletionCatalog.json
updated behavior
behavior was updated in FUSETOOLS2-996
=> FUSETOOLS2-1009 - update description of commands to be aligned with

demos/markdown/tutorial/tutorial.didact.md
=> FUSETOOLS2-957 - update tutorial to modified completion

CHANGELOG.md, package-lock.json, package.json
=> Prepare next development iteration 0.4.2
